[workspace]
authors = ["Seth Stadick <sstadick@gmail.com>"]
channels = [
    "https://prefix.dev/conda-forge",
    "https://conda.modular.com/max-nightly",
    "https://repo.prefix.dev/modular-community",
]
platforms = ["linux-64", "osx-arm64"]
preview = ["pixi-build"]

[package]
name = "hat"
version = "0.1.0"
license = "MIT"
description = "Helper utility for working with Mojo projects."

[package.build]
backend = { name = "pixi-build-mojo", version = "0.*", channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
    "https://repo.prefix.dev/modular-community",
] }

[package.host-dependencies]
mojo-compiler = "=0.26.1"

[package.build-dependencies]
mojo-compiler = "=0.26.1"
extramojo = "=0.20"

[package.run-dependencies]
mojo-compiler = "=0.26.1"

[tasks]
r = "mojo run main.mojo"
t = { cmd = "sh -c 'find ./tests -name test_*.mojo | xargs -I % mojo run -I . -D ASSERT=all %'" }

[dependencies]
mojo = "=0.26.1"
#extramojo = {path = "../../../ExtraMojo"}
extramojo = "=0.20"
hat = { path = "." }
